package com.oracle.svm.graalvisor.guestapi;

import static com.oracle.svm.graalvisor.utils.JsonUtils.json;
import static com.oracle.svm.graalvisor.utils.StringUtils.retrieveString;

import java.io.IOException;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.HashMap;
import java.util.Map;

import org.graalvm.nativeimage.IsolateThread;
import org.graalvm.nativeimage.ObjectHandle;
import org.graalvm.nativeimage.ObjectHandles;
import org.graalvm.nativeimage.PinnedObject;
import org.graalvm.nativeimage.RuntimeOptions;
import org.graalvm.nativeimage.c.function.CEntryPoint;
import org.graalvm.nativeimage.c.type.CCharPointer;
import org.graalvm.nativeimage.c.type.CTypeConversion;
import org.graalvm.word.WordFactory;

import com.oracle.svm.graalvisor.GraalVisor;

@SuppressWarnings("unused")
public class GuestAPI {

    protected static Method method;
    private volatile static GraalVisor.GraalVisorStruct graalVisorStructHost;
    private volatile static boolean functionRegistered = false;

    /**
     * Register the guest application class name in order to use reflection to invoke application
     * function. Each guest application should implement the function: {@code public static String
     * main(Map<String,Object> arguments)}
     *
     * @param applicationClassName fully-qualified class name of guest application
     * @throws ClassNotFoundException If this is happened on Substrate VM, check reflections
     *             configurations generated by tracing agent.
     * @throws NoSuchMethodException Make sure the class has the function implemented:
     *             {@code public static String
     *                                main(Map<String,Object> arguments)}
     */
    protected static void setApplicationClassName(String applicationClassName) throws ClassNotFoundException, NoSuchMethodException {
        Class<?> cls = Class.forName(applicationClassName);
        method = cls.getMethod("main", Map.class);
    }

    /**
     * Java entry point for graalvisor to call main function in guest application
     *
     * @param arguments arguments passed to the guest application main function
     * @return return String as invocation result
     * @throws InvocationTargetException indicates that there is exception happens inside *
     *             application function
     */
    protected static String invoke(String arguments) throws InvocationTargetException, IllegalAccessException {
        Map<String, Object> input = null;
        try {
            if (arguments != null && arguments.length() > 0) {
                input = json.mapFrom(arguments);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        if (input == null) {
            input = new HashMap<>();
        }
        try {
            if (method != null) {
                Object resultObject;
                try {
                    resultObject = method.invoke(null, new Object[]{input});
                    // TODO: catch ReflectiveOperationException | JNI exception
                } catch (Throwable t) {
                    Throwable cause = t.getCause() != null ? t.getCause() : t;
                    resultObject = "Exception in user function: " + cause.getClass().getCanonicalName() + ": " + cause.getMessage();
                    cause.printStackTrace();
                }
                return json.asString(resultObject);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        return "Fail to convert invocation result to json.";
    }

    /**
     * C entrypoint function for installing GraalVisor into guest isolate
     *
     * @param guestThread target guest isolate thread
     * @param graalvisorStruct pointer to the GraalVisor host
     */
    @CEntryPoint(name = "guest_install_graalvisor", include = AsGraalVisorGuest.class)
    private static void guestInstallGraalvisor(@CEntryPoint.IsolateThreadContext IsolateThread guestThread, GraalVisor.GraalVisorStruct graalvisorStruct) {
        if (graalVisorStructHost.isNonNull()) {
            return;
        }
        graalVisorStructHost = graalvisorStruct;
    }

    /**
     * C entrypoint function for invoke guest application main function.
     *
     * @param guestThread guest isolate thread
     * @param classHandle handle for fully-qualified class name
     * @param argumentHandle handle for fully-qualified class name
     * @return handle for invocation result
     * @throws InvocationTargetException indicates that there is exception happens inside
     *             application function
     */
    @CEntryPoint(name = "invoke_main_function", include = AsGraalVisorGuest.class)
    private static ObjectHandle invoke(@CEntryPoint.IsolateThreadContext IsolateThread guestThread, IsolateThread hostThread, ObjectHandle classHandle, ObjectHandle argumentHandle)
                    throws InvocationTargetException, IllegalAccessException {
        String functionName = retrieveString(classHandle);
        String arguments = retrieveString(argumentHandle);
        if (!functionRegistered) {
            try {
                setApplicationClassName(functionName);
            } catch (ClassNotFoundException | NoSuchMethodException e) {
                e.printStackTrace();
                return copyStringToHost(hostThread, "Function not found!");
            }
            functionRegistered = true;
        }
        return copyStringToHost(hostThread, invoke(arguments));
    }

    /**
     * C entry point to copy string into guest isolate heap space
     *
     * @param guestThread target guest isolate
     * @param cString CCharPointer to the beginning of the string
     * @return registered object handle for copied string, would is going to be used later for
     *         String retrieval.
     */
    @CEntryPoint(name = "guest_receive_string", include = AsGraalVisorGuest.class)
    private static ObjectHandle guestReceiveString(@CEntryPoint.IsolateThreadContext IsolateThread guestThread, CCharPointer cString) {
        /* Convert the C string to the target Java string. */
        String targetString = CTypeConversion.toJavaString(cString);
        /* Encapsulate the target string in a handle that can be returned to the source isolate. */
        return ObjectHandles.getGlobal().create(targetString);
    }

    /**
     * Guest API: Call host isolate to receive the string
     *
     * @param resultString String that allocated in guest heap space and need to be copied to the
     *            host.
     * @return {@code ObjectHandle} that points to the copy in host heap space.
     */
    protected static ObjectHandle copyStringToHost(IsolateThread hostThread, String resultString) {
        try (CTypeConversion.CCharPointerHolder cStringHolder = CTypeConversion.toCString(resultString)) {
            return graalVisorStructHost.getHostReceiveStringFunction().invoke(hostThread, cStringHolder.get());
        }
    }
}
