#!/bin/bash

function DIR {
    echo "$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
}

# Remove previous graalvisor pid file so that we can wait for the new one.
rm graalvisor.pid
# Launch graalvisor in background.
bash $(DIR)/graalvisor graalvisor.pid &> graalvisor.log &
# Wait for pid file.
while [ ! -s graalvisor.pid  ]; do sleep 0.1; done
# Attach gdb to graalvisor. Sudo is needed because we are attached across a PID namespace.
sudo gdb $(DIR)/build/native-image/polyglot-proxy $(cat graalvisor.pid)
