#!/bin/bash

function DIR {
    echo "$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
}

# Syntax: graalvisor [path to graalvisor.pid file]
pidfile=$1

function get_child_pid {
    ppid=$1
    # Note: under high load conditions, we need to wait for unshare to have childs.
    sleep .1
    # Note: if the child crashed, we don't want to wait forever.
    attempts=10 # TODO - needs to be fixed.
    for ((i=0; i<attempts; i++))
    do
        cpid=$(pgrep -P $ppid)
        [[ ! -z $cpid ]] && break
        sleep .1
    done
    echo $cpid
}

# Uncomment to enable strace. The log will be put next to the graalvisor binary.
#trace_syscalls="strace -f -o strace.log"

# This is important to ensure that we can load many (>100k) sandboxes.
# sudo sysctl -w vm.max_map_count=2000000

# Note 1: unshare is necessary so that graalvisor lives in a different pid namespace (required for svm snapshotting).
# Note 2: setarch is necessary to disable ASRL, which is relevant for svm snapshotting (accessible through context-sandbox).
# Note 3: G_SLICE makes GLIB ONLY use malloc/free and not weirder things like posix_memalign which aren't supported in mspaces.
# G_SLICE is important for the correct execution of the javascript-thumbnail test.
# For more information check https://web.mit.edu/barnowl/share/gtk-doc/html/glib/glib-running.html#G_SLICE
# Note 4: for large heaps, add `-Xmx128g` next to graalvisor.
UNSHARE_OPTS="--kill-child --map-root-user --keep-caps --mount-proc -f -p"
ARCH_OPTS="-R"
ALLOCATOR="$(DIR)/src/main/c/svm-snapshot/deps/dlmalloc/hydralloc.so"

$trace_syscalls unshare $UNSHARE_OPTS setarch $ARCH_OPTS env LD_PRELOAD=$ALLOCATOR G_SLICE=always-malloc $(DIR)/build/native-image/polyglot-proxy &

# The quest to find graalvisor's pid! Note that we want the pid as seen from the default namespace.
if [ ! -z "$pidfile" ]
then
    # PID of unshare (or strace).
    upid=$!
    # PID of graalvisor (or unshare).
    gpid=$(get_child_pid $upid)
    # If strace is being used, we need to go one level deeper.
    if [ ! -z "$trace_syscalls" ]
    then
        # PID of graalvisor.
        ggpid=$(get_child_pid $gpid)
        echo -n "$ggpid" > $pidfile
    else
        echo -n "$gpid" > $pidfile
    fi
fi

# Wait for graalvisor to terminate.
wait
