package org.graalvm.argo.graalvisor.function;

import java.util.Locale;

import org.graalvm.argo.graalvisor.sandboxing.SandboxProvider;

import com.oracle.svm.graalvisor.polyglot.PolyglotLanguage;

public class PolyglotFunction {
    private final String name;
    private final String entryPoint;
    private final PolyglotLanguage language;
    private SandboxProvider sprovider;
    /** isExecutable is used to check whether a function is binary generated by graalvm using PGO or not.
     * If it's binary then will be executed directly without being part of polyglot as a shared lib. */
    private final boolean isExecutable;

    public PolyglotFunction(String name, String entryPoint, String language, boolean isExecutable) {
        this.name = name;
        this.entryPoint = entryPoint;
        this.language = PolyglotLanguage.valueOf(language.toUpperCase(Locale.ROOT));
        this.isExecutable = isExecutable;
    }

    public String getName() {
        return name;
    }

    public String getEntryPoint() {
        return entryPoint;
    }

    public PolyglotLanguage getLanguage() {
        return language;
    }

    public void setSandboxProvider(SandboxProvider sprovider) {
        this.sprovider = sprovider;
    }

    public SandboxProvider getSandboxProvider() {
        return this.sprovider;
    }

    public boolean isExecutable() {
        return isExecutable;
    }
}
