plugins {
    id 'java'
    id "com.github.johnrengelman.shadow" version "7.1.0"
}

group 'com.jni'
version '1.0'

repositories {
    mavenCentral()
}

shadowJar() {
    configurations = [project.configurations.compileClasspath]
    from sourceSets.main.output
}

dependencies {
    implementation group: 'org.apache.commons', name: 'commons-lang3', version: '3.0'
}

jar {
    manifest {
        attributes(
                'Main-Class': 'com.jni.AESEncryption',
                'Class-Path': configurations.runtimeClasspath.files.collect { it.getName() }.join(' ')
        )
    }
}
