plugins {
    id 'java'
    id "com.github.johnrengelman.shadow" version "7.1.0"
}

group 'com.filehashing'
version '1.0'

repositories {
    mavenCentral()
}

shadowJar() {
    configurations = [project.configurations.compileClasspath]
    from sourceSets.main.output
}

dependencies {
    implementation group: 'javax.xml.bind', name: 'jaxb-api', version: '2.1' 
}

jar {
    manifest {
        attributes(
                'Main-Class': 'com.filehashing.FileHashing',
                'Class-Path': configurations.runtimeClasspath.files.collect { it.getName() }.join(' ')
        )
    }
}

test {
    useJUnitPlatform()
}
